version:
  label: "1.1.2"
  isBeta: true
  usesBetaData: true
  officialUrl: "https://nomad-lab.eu/prod/v1/gui"

image:
    tag: "latest"
    pullPolicy: "Always"

proxy:
  nodePort: 30008
  nodeIP: '130.183.207.81'
  external:
    host: "nomad-lab.eu"
    path: "/prod/v1/test"

gui:
  debug: true

app:
  replicas: 2
  worker: 4

worker:
  replicas: 2
  routing: "queue"
  processes: 10
  nomadNodeType: "prod-worker"

elastic:
  host: elasticsearch.elasticsearch-7.svc.cluster.local
  port: 9200

mongo:
  host: rs0/mongodb-0.mongo.mongodb.svc.cluster.local,mongodb-1.mongo.mongodb.svc.cluster.local,mongodb-2.mongo.mongodb.svc.cluster.local

logstash:
  host: logstash.elk.svc.cluster.local

dbname: nomad_test_v1

uploadurl: 'http://nomad-lab.eu/prod/rae/test/api/uploads'

client:
  passwordSecret: 'nomad-keycloak-password'

keycloak:
  serverUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  passwordSecret: 'nomad-keycloak-password'
  realmName: 'fairdi_nomad_prod'
  clientId: 'nomad_public'
  admin_user_id: '82efac55-6187-408c-8027-b98580c0e1c5'

volumes:
  prefixSize: 1
  public: /nomad/fairdi/test/fs/public
  staging: /nomad/fairdi/test/fs/staging
  tmp: /nomad/fairdi/test/fs/tmp
  nomad: /nomad
  archiveVersionSuffix: v1

mail:
  enabled: true
  host: 'mailrelay.mpcdf.mpg.de'
  port: 25
  from: 'webmaster@nomad-coe.eu'
