apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nomad.fullname" . }}-proxy-config
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-proxy-config
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    {{ if .Values.north.enabled }}
    # top-level http config for websocket headers
    # If Upgrade is defined, Connection = upgrade
    # If Upgrade is empty, Connection = close
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    {{ end }}

    server {
      listen        80;
      server_name   www.example.com;
      proxy_set_header Host $host;

      proxy_connect_timeout {{ .Values.proxy.timeout }};
      proxy_read_timeout {{ .Values.proxy.timeout }};
      proxy_pass_request_headers      on;
      underscores_in_headers          on;

      {{ if .Values.gui.gzip }}
      gzip_min_length     1000;
      gzip_buffers        4 8k;
      gzip_http_version   1.0;
      gzip_disable        "msie6";
      gzip_vary           on;
      gzip on;
      gzip_proxied any;
      gzip_types
          text/css
          text/javascript
          text/xml
          text/plain
          application/javascript
          application/x-javascript
          application/json;
      {{ end }}

      location / {
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ {{ .Values.proxy.external.path }}\/?(gui)?$ {
        rewrite ^ {{ .Values.proxy.external.path }}/gui/ permanent;
      }

      location {{ .Values.proxy.external.path }}/gui/ {
        proxy_intercept_errors on;
        error_page 404 = @redirect_to_index;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location @redirect_to_index {
        rewrite ^ {{ .Values.proxy.external.path }}/gui/index.html break;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location {{ .Values.proxy.external.path }}/docs/ {
        proxy_intercept_errors on;
        error_page 404 = @redirect_to_index_docs;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location @redirect_to_index_docs {
        rewrite ^ {{ .Values.proxy.external.path }}/docs/index.html break;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ \/gui\/(service-worker\.js|meta\.json)$ {
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ /api/v1/uploads(/?$|.*/raw|.*/bundle?$)  {
        client_max_body_size 35g;
        proxy_request_buffering off;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ /api/v1/.*/download {
        proxy_buffering off;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ /api/v1/entries/edit {
        proxy_buffering off;
        proxy_read_timeout {{ .Values.proxy.editTimeout }};
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      {{ if .Values.north.enabled }}
      location {{ .Values.proxy.external.path }}/north/ {
          client_max_body_size 500m;
          proxy_pass http://{{ include "jupyterhub.fullname" . }}-proxy-public;

          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          # websocket headers
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_set_header X-Scheme $scheme;

          proxy_buffering off;
      }
      {{ end }}

    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-proxy
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-proxy
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.gui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nomad.name" . }}-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nomad.name" . }}-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ if .Values.roll }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
    spec:
      containers:
      - name: {{ include "nomad.name" . }}-proxy
        image: "nginx:1.13.9-alpine"
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
        livenessProbe:
          httpGet:
            path: "{{ .Values.proxy.external.path }}/alive"
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: {{ .Values.proxy.timeout }}
        readinessProbe:
          httpGet:
            path: "{{ .Values.proxy.external.path }}/alive"
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
      nodeSelector:
        nomadtype: public
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "nomad.fullname" . }}-proxy-config
          items:
          - key: nginx.conf
            path: default.conf
      - name: log
        emptyDir: {}
